drop table brian.reviews;

create table brian.reviews(

user_id varchar(50),
review_id varchar(50),
stars int,
date date,
text varchar(50),
type varchar(16),  
business_id varchar(50),
user_id2 varchar(50),
funny_votes int,
useful_votes int,
votes_cool int,
review varchar(8000)
);


truncate table brian.reviews;
copy brian.reviews from 's3://ncarb-dsteam/Brian/Yelp/reviews.tsv'
credentials 'aws_access_key_id=[access_key];aws_secret_access_key=[secret]'
delimiter '\t'
REMOVEQUOTES
IGNOREHEADER as 1
DATEFORMAT AS 'YYYY-MM-DD';

select * from brian.reviews where lower(review) like '%awesome%' limit 4000;


drop table brian.tips;
create table brian.tips (
business_id varchar(50),
user_id varchar(50), date date, text varchar(8000),likes int,type  varchar(7)
);

truncate table brian.tips;
copy brian.tips from 's3://ncarb-dsteam/Brian/Yelp/tips.tsv'
credentials 'aws_access_key_id=[access_key];aws_secret_access_key=[secret]'
delimiter '\t'
REMOVEQUOTES
IGNOREHEADER as 1
DATEFORMAT AS 'YYYY-MM-DD';

drop table brian.checkins;
create table brian.checkins (
business_id varchar(50),  "9-Friday" int, "7-Friday" int, "13-Wednesday" int,
"17-Saturday" int,"13-Sunday" int,"17-Wednesday" int,"10-Sunday" int,
"18-Thursday" int,"14-Saturday" int,"22-Friday" int,"15-Monday" int,
"15-Thursday" int,"16-Tuesday" int,"21-Thursday" int,"13-Monday" int,
"14-Thursday" int,"12-Friday" int,"12-Monday" int,"9-Monday" int, 
"18-Wednesday" int,"15-Tuesday" int,"8-Thursday" int, "17-Friday" int,
"17-Thursday" int,"11-Tuesday" int,"12-Thursday" int,"10-Thursday" int,
"8-Monday" int, "9-Thursday" int, "9-Sunday" int, "18-Monday" int,
"19-Saturday" int,"7-Saturday" int, "11-Friday" int,"11-Thursday" int,
"17-Tuesday" int,"6-Friday" int, "12-Tuesday" int,"7-Thursday" int, 
"18-Tuesday" int,"16-Monday" int,"19-Tuesday" int,"12-Wednesday" int,
"10-Saturday" int,"13-Tuesday" int,"16-Thursday" int,"10-Friday" int,
"20-Tuesday" int,"4-Thursday" int, "9-Tuesday" int, "10-Tuesday" int,
"4-Sunday" int, "4-Monday" int, "11-Saturday" int,"11-Monday" int,
"10-Monday" int,"6-Saturday" int, "5-Monday" int, "6-Wednesday" int, 
"6-Sunday" int, "6-Monday" int, "5-Friday" int, "9-Wednesday" int, 
"5-Saturday" int, "4-Saturday" int, "9-Saturday" int, "7-Wednesday" int, 
"7-Tuesday" int, "7-Monday" int, "3-Thursday" int, "3-Wednesday" int, 
"8-Friday" int, "8-Saturday" int, "10-Wednesday" int,"8-Tuesday" int, 
"8-Wednesday" int, "5-Thursday" int, "6-Tuesday" int, "8-Sunday" int, 
"19-Thursday" int,"13-Thursday" int,"20-Thursday" int,"13-Friday" int,
"15-Friday" int,"17-Sunday" int,"19-Friday" int,"15-Sunday" int,
"15-Wednesday" int,"1-Friday" int, "19-Sunday" int,"19-Monday" int,
"16-Friday" int,"12-Sunday" int,"4-Friday" int, "18-Friday" int,
"18-Saturday" int,"16-Saturday" int,"14-Tuesday" int,"13-Saturday" int,
"14-Friday" int,"14-Monday" int,"16-Sunday" int,"17-Monday" int,
"5-Wednesday" int,"20-Saturday" int,"11-Sunday" int,"15-Saturday" int,
"3-Tuesday" int, "19-Wednesday" int,"12-Saturday" int,"4-Tuesday" int, 
"7-Sunday" int, "14-Sunday" int,"6-Thursday" int, "16-Wednesday" int,
"22-Thursday" int,"22-Monday" int,"23-Friday" int,"0-Friday" int, 
"0-Saturday" int, "0-Monday" int, "11-Wednesday" int,"20-Friday" int,
"21-Friday" int,"21-Monday" int,"21-Tuesday" int,"21-Wednesday" int,
"22-Sunday" int,"18-Sunday" int,"14-Wednesday" int,"20-Monday" int,
"20-Wednesday" int,"23-Tuesday" int,"21-Saturday" int,"0-Thursday" int, 
"3-Friday" int, "20-Sunday" int,"22-Wednesday" int,"5-Sunday" int, 
"3-Monday" int, "3-Sunday" int, "5-Tuesday" int, "4-Wednesday" int,
 "22-Saturday" int,"3-Saturday" int, "2-Saturday" int, "22-Tuesday" int,"1-Sunday" int, "21-Sunday" int,"2-Wednesday" int, "1-Wednesday" int, "2-Sunday" int, "0-Tuesday" int, "23-Thursday" int,"23-Sunday" int,"2-Tuesday" int,"2-Thursday" int, "23-Monday" int,"2-Monday" int, "1-Saturday" int, "2-Friday" int, "23-Saturday" int,"0-Wednesday" int, "1-Tuesday" int, "1-Thursday" int, "23-Wednesday" int,"1-Monday" int, 
 "0-Sunday" int
);

truncate table brian.checkins;
copy brian.checkins from 's3://ncarb-dsteam/Brian/Yelp/checkins.tsv'
credentials 'aws_access_key_id=[access_key];aws_secret_access_key=[secret]'
delimiter '\t'
REMOVEQUOTES
IGNOREHEADER as 1
DATEFORMAT AS 'YYYY-MM-DD';


drop table brian.business;
create table brian.business (
business_id varchar(50),
name varchar(500),
open_sun varchar(50),
closed_sun varchar(50),
open_mon varchar(50),
closed_mon varchar(50),
open_tues varchar(50),
closed_tues varchar(50),
open_wed varchar(50),
closed_wed varchar(50),
open_thu varchar(50),
closed_thu varchar(50),
open_fri varchar(50),
closed_fri varchar(50),
open_sat varchar(50),
closed_sat varchar(50),
 full_address varchar(500),
city varchar(50),
state varchar(50),
review_count varchar(50),
is_open varchar(50),
stars varchar(50),
lat varchar(50),
lon varchar(50),
type varchar(50),
categories varchar(500),
by_appt varchar(50),
price_range varchar(50),
happy_hour varchar(50),
smoking varchar(50),
byob varchar(50),
corkage varchar(50),
byob_corkage varchar(50),
 alcohol varchar(50),
 waiter_service varchar(50),
 wifi varchar(20)
);

truncate table brian.business;
copy brian.business from 's3://ncarb-dsteam/Brian/Yelp/businesses.tsv'
credentials 'aws_access_key_id=[access_key];aws_secret_access_key=[secret]'
delimiter '\t'
REMOVEQUOTES
IGNOREHEADER as 1
DATEFORMAT AS 'YYYY-MM-DD';

drop table brian.user;
create table brian.user(
user_id varchar(50),
useful_votes int,
funny_votes int,
cool_votes int,
average_stars float,
fan_count int,
friend_count int,
hot_compliments int,
writer_compliments int,
photos_compliments int,
cool_compliments int,
funny_compliments int,
cute_compliments int,
plain_compliments int,
name varchar(200)
);

truncate table brian.user;
copy brian.user from 's3://ncarb-dsteam/Brian/Yelp/users.tsv'
credentials 'aws_access_key_id=[access_key];aws_secret_access_key=[secret]'
delimiter '\t'
REMOVEQUOTES
IGNOREHEADER as 1
DATEFORMAT AS 'YYYY-MM-DD';

--Create nem top categories
drop table brian.top_categories;
create table brian.top_categories ( categories varchar(4000), avg_stars float, review_count int, biz_count int);
truncate table brian.top_categories;
insert into brian.top_categories
select
        b.categories,
        avg(r.stars * 1.000000) avg_stars,
        count(8) review_count,
        count(distinct r.business_id) biz_count
    from
        brian.business b
    join
        brian.reviews r
            on r.business_id = b.business_id     --where lower(b.categories) like '%bail bond%'
             
    group by
        b.categories    
    having
        count(8) > 29    and count(distinct r.business_id) > 5 and avg(r.stars * 1.0000000) >=4
    order by
        2 desc--, random()
        limit 500;

--Take it away, bottom categories
drop table brian.bottom_categories;
create table brian.bottom_categories ( categories varchar(4000), avg_stars float, review_count int, biz_count int);
truncate table brian.bottom_categories;
insert into brian.bottom_categories
select
        b.categories,
        avg(r.stars * 1.000000) avg_stars,
        count(8) review_count,
        count(distinct r.business_id) biz_count 
    from
        brian.business b
    join
        brian.reviews r
            on r.business_id = b.business_id     --where lower(b.categories) like '%bail bond%'
             
    group by
        b.categories    
    having
        count(8) > 29    and count(distinct r.business_id) > 5 -- and avg(r.stars * 1.0000000) <3
        order by avg(r.stars * 1.0000000) limit 500;

drop table brian.random_reviews;
create table brian.random_reviews (review_id varchar(50));
insert into brian.random_reviews
select review_id from brian.reviews r join brian.business b on b.business_id = r.business_id where b.categories != '' order by random() limit 100000;


drop table brian.dtm;
create table brian.dtm (
categories varchar(255),
X varchar(13),
accessori smallint,
account smallint,
activ smallint,
acupunctur smallint,
adopt smallint,
adult smallint,
advertis smallint,
advis smallint,
afghan smallint,
african smallint,
agenc smallint,
agent smallint,
aid smallint,
air smallint,
airlin smallint,
airport smallint,
allergist smallint,
alter smallint,
amateur smallint,
american smallint,
ammo smallint,
amus smallint,
anesthesiologist smallint,
anim smallint,
antiqu smallint,
apart smallint,
applianc smallint,
aquarium smallint,
arabian smallint,
arcad smallint,
archeri smallint,
architect smallint,
arena smallint,
argentin smallint,
art smallint,
artist smallint,
asian smallint,
assist smallint,
astrolog smallint,
auction smallint,
audio smallint,
audiologist smallint,
australian smallint,
austrian smallint,
auto smallint,
automot smallint,
babi smallint,
baden smallint,
bagel smallint,
bail smallint,
bakeri smallint,
ballet smallint,
balloon smallint,
bangladeshi smallint,
bank smallint,
bankruptci smallint,
bar smallint,
barbequ smallint,
barber smallint,
barr smallint,
bartend smallint,
basketbal smallint,
basqu smallint,
bat smallint,
bath smallint,
batteri smallint,
bavarian smallint,
beach smallint,
beauti smallint,
bed smallint,
beer smallint,
belgian smallint,
bespok smallint,
beverag smallint,
bike smallint,
bistro smallint,
blind smallint,
blow smallint,
blue smallint,
board smallint,
boardingpet smallint,
boat smallint,
bodi smallint,
bondsmen smallint,
book smallint,
bookstor smallint,
boot smallint,
booth smallint,
botan smallint,
bowl smallint,
box smallint,
brasseri smallint,
brazilian smallint,
breakfast smallint,
brew smallint,
breweri smallint,
bridal smallint,
british smallint,
broker smallint,
brunch smallint,
bubbl smallint,
buddhist smallint,
buffet smallint,
build smallint,
burger smallint,
burmes smallint,
bus smallint,
buse smallint,
busi smallint,
butcher smallint,
buyer smallint,
cabaret smallint,
cabinetri smallint,
cafe smallint,
cafeteria smallint,
cage smallint,
cajuncreol smallint,
cambodian smallint,
camp smallint,
campground smallint,
canadian smallint,
candi smallint,
cannabi smallint,
cantones smallint,
car smallint,
card smallint,
cardiologist smallint,
care smallint,
career smallint,
caribbean smallint,
carpet smallint,
cashingpayday smallint,
casino smallint,
castl smallint,
cater smallint,
cemeteri smallint,
center smallint,
challeng smallint,
champagn smallint,
chang smallint,
charter smallint,
has_check smallint,
chees smallint,
cheesesteak smallint,
chef smallint,
chi smallint,
chicken smallint,
child smallint,
children smallint,
chimney smallint,
chines smallint,
chip smallint,
chiropractor smallint,
chocolati smallint,
christma smallint,
church smallint,
cinema smallint,
class smallint,
clean smallint,
cleaner smallint,
climb smallint,
clinic smallint,
cloth smallint,
clown smallint,
club smallint,
coach smallint,
coat smallint,
cocktail smallint,
coffe smallint,
coffeeshop smallint,
colleg smallint,
colombian smallint,
comedi smallint,
comfort smallint,
comic smallint,
commerci smallint,
communiti smallint,
comput smallint,
conditioninghvac smallint,
consign smallint,
contractor smallint,
control smallint,
conveni smallint,
cook smallint,
cosmet smallint,
cosmetolog smallint,
costum smallint,
counsel smallint,
countri smallint,
courier smallint,
cours smallint,
court smallint,
courthous smallint,
cpr smallint,
craft smallint,
cream smallint,
credit smallint,
creperi smallint,
crimin smallint,
croatian smallint,
crochet smallint,
csa smallint,
cuban smallint,
cultur smallint,
cupcak smallint,
currenc smallint,
curri smallint,
custom smallint,
cycl smallint,
czech smallint,
damag smallint,
danc smallint,
data smallint,
day smallint,
dealer smallint,
decor smallint,
defens smallint,
deli smallint,
delicatessen smallint,
deliveri smallint,
dentist smallint,
dentistri smallint,
depart smallint,
dermatologist smallint,
design smallint,
dessert smallint,
detail smallint,
diagnost smallint,
dim smallint,
diner smallint,
disc smallint,
discount smallint,
distilleri smallint,
dive smallint,
divorc smallint,
djs smallint,
doctor smallint,
dog smallint,
doityourself smallint,
dominican smallint,
donair smallint,
donut smallint,
door smallint,
doula smallint,
dri smallint,
drive smallint,
drugstor smallint,
dryout smallint,
drywal smallint,
dui smallint,
dvds smallint,
ear smallint,
eastern smallint,
educ smallint,
egyptian smallint,
electrician smallint,
electron smallint,
elementari smallint,
embroideri smallint,
employ smallint,
endocrinologist smallint,
endodontist smallint,
entertain smallint,
equip smallint,
estat smallint,
ethiopian smallint,
ethnic smallint,
european smallint,
event smallint,
exchang smallint,
extens smallint,
eye smallint,
eyelash smallint,
eyewear smallint,
fabric smallint,
face smallint,
falafel smallint,
famili smallint,
farmer smallint,
fashion smallint,
fast smallint,
fenc smallint,
fertil smallint,
festiv smallint,
fidel smallint,
filipino smallint,
financi smallint,
fire smallint,
firearm smallint,
fireplac smallint,
firewood smallint,
firework smallint,
first smallint,
fish smallint,
fit smallint,
fixtur smallint,
flavor smallint,
flea smallint,
flight smallint,
floor smallint,
florist smallint,
flower smallint,
fondu smallint,
food smallint,
formal smallint,
frame smallint,
french smallint,
frozen smallint,
fruit smallint,
funer smallint,
furnitur smallint,
fusion smallint,
galleri smallint,
game smallint,
garag smallint,
garden smallint,
gas smallint,
gastroenterologist smallint,
gastropub smallint,
gate smallint,
gay smallint,
gear smallint,
gelato smallint,
general smallint,
german smallint,
gift smallint,
glass smallint,
glide smallint,
glutenfre smallint,
gold smallint,
golf smallint,
good smallint,
govern smallint,
graphic smallint,
greek smallint,
groceri smallint,
groomer smallint,
guest smallint,
gun smallint,
gunrifl smallint,
gutter smallint,
gym smallint,
gymnast smallint,
gynecologist smallint,
hair smallint,
haitian smallint,
halal smallint,
hall smallint,
handyman smallint,
hang smallint,
hardwar smallint,
hat smallint,
haul smallint,
hawaiian smallint,
health smallint,
hear smallint,
heat smallint,
herb smallint,
high smallint,
hike smallint,
himalayannepales smallint,
hindu smallint,
histor smallint,
hobbi smallint,
home smallint,
hookah smallint,
hors smallint,
horseback smallint,
hospic smallint,
hospit smallint,
hostel smallint,
hot smallint,
hotel smallint,
hous smallint,
hungarian smallint,
hypnosishypnotherapi smallint,
iberian smallint,
ice smallint,
imag smallint,
immigr smallint,
indian smallint,
indonesian smallint,
injuri smallint,
inspector smallint,
instal smallint,
instruct smallint,
instrument smallint,
insul smallint,
insur smallint,
interior smallint,
intern smallint,
internet smallint,
invest smallint,
investig smallint,
irish smallint,
irrig smallint,
italian smallint,
izakaya smallint,
japanes smallint,
jazz smallint,
jewelri smallint,
juic smallint,
junk smallint,
karaok smallint,
kart smallint,
kebab smallint,
key smallint,
kid smallint,
kitchen smallint,
knit smallint,
korean smallint,
kosher smallint,
laboratori smallint,
lactat smallint,
lake smallint,
landmark smallint,
landscap smallint,
languag smallint,
laotian smallint,
laser smallint,
latin smallint,
laundri smallint,
law smallint,
lawyer smallint,
leather smallint,
lebanes smallint,
legal smallint,
leisur smallint,
lessonsschool smallint,
librari smallint,
lice smallint,
life smallint,
light smallint,
limo smallint,
lingeri smallint,
litig smallint,
liveraw smallint,
loan smallint,
local smallint,
locksmith smallint,
loss smallint,
loung smallint,
luggag smallint,
mag smallint,
magazin smallint,
magician smallint,
mailbox smallint,
makeup smallint,
malaysian smallint,
manag smallint,
market smallint,
martial smallint,
masonryconcret smallint,
mass smallint,
massag smallint,
matchmak smallint,
matern smallint,
mattress smallint,
meat smallint,
media smallint,
medic smallint,
medicin smallint,
medit smallint,
mediterranean smallint,
men smallint,
mental smallint,
merchandis smallint,
metal smallint,
mexican smallint,
middl smallint,
midwiv smallint,
mini smallint,
mirror smallint,
mobil smallint,
modern smallint,
mongolian smallint,
moroccan smallint,
mortgag smallint,
mosqu smallint,
motor smallint,
motorcycl smallint,
mountain smallint,
mover smallint,
museum smallint,
music smallint,
musician smallint,
nail smallint,
nanni smallint,
naturopathicholist smallint,
neurologist smallint,
has_new smallint,
newspap smallint,
nightlif smallint,
nose smallint,
notari smallint,
nurseri smallint,
nutritionist smallint,
obstetrician smallint,
occup smallint,
offic smallint,
offici smallint,
oil smallint,
oncologist smallint,
opera smallint,
ophthalmologist smallint,
optician smallint,
optometrist smallint,
oral smallint,
organ smallint,
orient smallint,
orthodontist smallint,
orthopedist smallint,
orthot smallint,
osteopath smallint,
outdoor smallint,
outlet smallint,
paddleboard smallint,
paint smallint,
paintbal smallint,
painter smallint,
pakistani smallint,
park smallint,
part smallint,
parti smallint,
pasta smallint,
patisseriecak smallint,
pawn smallint,
payrol smallint,
pediatr smallint,
pediatrician smallint,
perform smallint,
periodontist smallint,
perman smallint,
persianiranian smallint,
person smallint,
peruvian smallint,
pest smallint,
pet smallint,
pharmaci smallint,
phone smallint,
photo smallint,
photograph smallint,
photographi smallint,
physic smallint,
physician smallint,
piano smallint,
pierc smallint,
pilat smallint,
pita smallint,
pizza smallint,
plan smallint,
plate smallint,
playground smallint,
plaza smallint,
plumb smallint,
plus smallint,
podiatrist smallint,
pole smallint,
polic smallint,
polish smallint,
pool smallint,
popup smallint,
portugues smallint,
post smallint,
pot smallint,
poutineri smallint,
powder smallint,
practic smallint,
prepar smallint,
preschool smallint,
pressur smallint,
pretzel smallint,
print smallint,
printingtshirt smallint,
privat smallint,
product smallint,
profession smallint,
propan smallint,
properti smallint,
prosthet smallint,
protect smallint,
provid smallint,
psychiatrist smallint,
psychic smallint,
psychologist smallint,
pub smallint,
public smallint,
pulmonologist smallint,
race smallint,
radio smallint,
radiologist smallint,
raftingkayak smallint,
ramen smallint,
rang smallint,
real smallint,
record smallint,
recoveri smallint,
recreat smallint,
recycl smallint,
refinish smallint,
reflexolog smallint,
registr smallint,
rehabilit smallint,
rehears smallint,
reiki smallint,
religi smallint,
remov smallint,
rental smallint,
repair smallint,
repairmainten smallint,
has_resort smallint,
restaur smallint,
restor smallint,
retir smallint,
retreat smallint,
reupholsteri smallint,
rheumatologist smallint,
ride smallint,
rim smallint,
rink smallint,
rock smallint,
rolf smallint,
roof smallint,
room smallint,
rug smallint,
russian smallint,
salad smallint,
sale smallint,
salesinstal smallint,
salon smallint,
salvadoran smallint,
sandwich smallint,
sauna smallint,
sausag smallint,
scandinavian smallint,
school smallint,
scottish smallint,
screen smallint,
scuba smallint,
seafood smallint,
secur smallint,
self smallint,
septic smallint,
serbo smallint,
servic smallint,
servicenonprofit smallint,
session smallint,
sew smallint,
shade smallint,
shanghaines smallint,
share smallint,
shave smallint,
shelter smallint,
ship smallint,
shoe smallint,
shop smallint,
shred smallint,
shutter smallint,
shuttl smallint,
signmak smallint,
singaporean smallint,
sit smallint,
size smallint,
skate smallint,
ski smallint,
skin smallint,
skydiv smallint,
smog smallint,
smoothi smallint,
soccer smallint,
social smallint,
solar smallint,
soul smallint,
soup smallint,
southern smallint,
souvenir smallint,
space smallint,
spanish smallint,
spas smallint,
special smallint,
specialti smallint,
speech smallint,
spice smallint,
spirit smallint,
sport smallint,
spray smallint,
stadium smallint,
stage smallint,
stand smallint,
station smallint,
stationeri smallint,
steakhous smallint,
stereo smallint,
storag smallint,
store smallint,
street smallint,
studio smallint,
stylist smallint,
sugar smallint,
sum smallint,
summer smallint,
suppli smallint,
surf smallint,
surgeon smallint,
surgerylasik smallint,
sushi smallint,
sweep smallint,
swim smallint,
swimwear smallint,
swiss smallint,
synagogu smallint,
has_system smallint,
szechuan smallint,
has_tag smallint,
tai smallint,
taiwanes smallint,
talent smallint,
tan smallint,
tapa smallint,
tapassmal smallint,
tattoo smallint,
tax smallint,
taxi smallint,
tea smallint,
teacher smallint,
team smallint,
technic smallint,
telecommun smallint,
televis smallint,
templ smallint,
tenni smallint,
teppanyaki smallint,
test smallint,
texmex smallint,
thai smallint,
theatr smallint,
therapi smallint,
therapist smallint,
thrift smallint,
throat smallint,
ticket smallint,
tint smallint,
tire smallint,
tobacco smallint,
tour smallint,
tow smallint,
toy smallint,
track smallint,
tradit smallint,
train smallint,
trainer smallint,
trampolin smallint,
transport smallint,
travel smallint,
tree smallint,
trinidadian smallint,
trophi smallint,
truck smallint,
tub smallint,
turkish smallint,
tutor smallint,
ukrainian smallint,
uniform smallint,
has_union smallint,
univers smallint,
urgent smallint,
urologist smallint,
use smallint,
util smallint,
uzbek smallint,
vacat smallint,
valet smallint,
vape smallint,
vegan smallint,
vegetarian smallint,
veggi smallint,
vehicl smallint,
vendor smallint,
venezuelan smallint,
venu smallint,
veterinarian smallint,
video smallint,
videofilm smallint,
videograph smallint,
vietnames smallint,
vintag smallint,
vinyl smallint,
vocat smallint,
walk smallint,
walker smallint,
walkin smallint,
wash smallint,
washer smallint,
watch smallint,
water smallint,
wax smallint,
wear smallint,
web smallint,
wed smallint,
weight smallint,
wheel smallint,
wholesal smallint,
wig smallint,
window smallint,
windshield smallint,
wine smallint,
wineri smallint,
wing smallint,
wok smallint,
women smallint,
yelp smallint,
yoga smallint,
yogurt smallint,
zoo smallint);

truncate table brian.dtm;
copy brian.dtm from 's3://ncarb-dsteam/Brian/Yelp/dtm.tsv'
credentials 'aws_access_key_id=[access_key];aws_secret_access_key=[secret]'
delimiter '\t'
REMOVEQUOTES
IGNOREHEADER as 1;

UNLOAD ('select b.categories, r.stars, u.*
from brian.business b
join brian.reviews r on r.business_id = b.business_id
join brian.user u on u.user_id = r.user_id
join brian.random_reviews rr on rr.review_id = r.review_id
join brian.dtm dtm on dtm.categories = b.categories
where b.categories != ''''')
TO 's3://ncarb-dsteam/Brian/Yelp/df.dtm.tsv'
credentials 'aws_access_key_id=[access_key];aws_secret_access_key=[secret]'
delimiter '\t';
