library(tm)
inspect(docs[2])
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeWords, stopwords("english"))
library(SnowballC)
docs <- tm_map(docs, stemDocument)
detach('package:SnowballC')
inspect(docs)
docs <- tm_map(docs, stripWhitespace)
inspect(docs)
tdm <- TermDocumentMatrix(docs)
inspect(tdm)
findFreqTerms(tdm,lowfreq = 10)
findAssocs(tdm,"women",corlimit = .1)
tdm.common.60 <- removeSparseTerms(tdm,sparse=.6)
tdm.common.20 <- removeSparseTerms(tdm,sparse=.2)
df <- data.frame(inspect(tdm))
library(dplyr)
df$diff <- df$joy.tsv - df$misery.tsv
df$pct.diff <- df$diff/(df$joy.tsv + df$misery.tsv)
df$names <- row.names(df)
head(arrange(filter(df, misery.tsv > 0), desc(diff)))
head(arrange(df, desc(joy.tsv)))
head(arrange(df, desc(misery.tsv)))


head(arrange(filter(df, misery.tsv>0), desc(pct.diff)))
head(arrange(filter(df,joy.tsv>0), pct.diff))
head(arrange(filter(df, misery.tsv>0), desc(diff)))
head(arrange(filter(df,joy.tsv>0), diff))
head(df)

