library(tm)
inspect(docs)
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeWords, stopwords("english"))
library(SnowballC)
docs <- tm_map(docs, stemDocument)
detach('package:SnowballC')
inspect(docs)
docs <- tm_map(docs, stripWhitespace)
inspect(docs)
tdm <- TermDocumentMatrix(docs)
inspect(tdm)
findFreqTerms(tdm,lowfreq = 200)
findAssocs(tdm,"lost",corlimit = .1)
tdm.common.60 <- removeSparseTerms(tdm,sparse=.6)
tdm.common.20 <- removeSparseTerms(tdm,sparse=.2)
